LOCK_SERVO_PIN = 11
LOCKED_LED = 12
TESTING_LED = 16
UNLOCKED_LED = 18
LOCK_SERVO_UNLOCKED = 100
LOCK_SERVO_LOCKED = 0
BUTTON_PIN = 22
BUTTON_DOWN = False
BUTTON_UP = True
POSITIVE_THRESHOLD = 2000.0
COMPONENT_NUMBER = 80
TRAINING_FILE = 'training.xml'
POSITIVE_DIR = './training/positive'
NEGATIVE_DIR = './training/negative'
POSITIVE_LABEL = 1
NEGATIVE_LABEL = 2
FACE_WIDTH = 92
FACE_HEIGHT = 112
HAAR_FACES = 'haarcascade_frontalface_alt.xml'
HAAR_SCALE_FACTOR = 1.3
HAAR_MIN_NEIGHBORS = 4
HAAR_MIN_SIZE = (30, 30)
DEBUG_IMAGE = 'capture.pgm'

def get_camera():
    import picam
    return picam.OpenCVCapture()
